import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Loafer Tan Leather",
    brand: "By Clarks's",
    price: 5000,
    inStock:true,
    fastDelivery: true,
    rating: 3,
    imageUrl: "/Assets/clarks_loafer.jpeg" ,
    categoryName: "Loafers",
  },
  {
    _id: uuid(),
    title: "Ronnie Step Tan Leather",
    brand : "Clarks's",
    price: 3000,
    inStock:true,
    fastDelivery: false,
    rating: 3,
    imageUrl: "/Assets/ronnie_loafer.jpeg", 
    categoryName: "Loafers",
  },
  {
    _id: uuid(),
    title: "Whiddon Loafer Black Leather",
    brand: "Whiddon",
    price: 3200,
    inStock:true,
    fastDelivery: false,
    rating: 5,
    imageUrl: "/Assets/whidon_loafer.jpeg",
    categoryName: "Loafers",
  },
  {
    _id: uuid(),
    title: "Markman Dark Tan Leather",
    brand: "Markman",
    price: 5200,
    inStock:true,
    fastDelivery: true,
    rating: 3,
    imageUrl: "/Assets/brown_loafer.jpeg",
    categoryName: "Loafers",
  },
  {
    _id: uuid(),
    title: "Black Chelsea",
    brand: "By Clarks's",
    price: 4500,
    inStock:false,
    fastDelivery: true,
    rating: 4,
    imageUrl: "/Assets/black_chelsea.jpeg" ,
    categoryName: "Chelsea",
  },
  {
    _id: uuid(),
    title: "Clarks's Velvet Chelsea",
    brand : "Clarks's",
    price: 4000,
    inStock:true,
    fastDelivery: true,
    rating: 3,
    imageUrl: "/Assets/black_velvet_chelsea.jpeg", 
    categoryName: "Chelsea",
  },
  {
    _id: uuid(),
    title: "Whiddon Black Casual Shoes",
    brand: "Whiddon",
    price: 3200,
    inStock:true,
    fastDelivery: true,
    rating: 4,
    imageUrl: "/Assets/black_casual.jpeg",
    categoryName: "Casuals",
  },
  {
    _id: uuid(),
    title: "Bumpty Leather Shoes",
    brand: "Bumpty",
    price: 4200,
    inStock:false,
    fastDelivery: false,
    rating: 4,
    imageUrl: "/Assets/bumpty_leather.jpeg",
    categoryName: "Casuals",
  },
  {
    _id: uuid(),
    title: "Clark's Combination Leather Shoes",
    brand: "Clark's",
    price: 5200,
    inStock:true,
    fastDelivery: false,
    rating: 3,
    imageUrl: "/Assets/bumpty_leather.jpeg",
    categoryName: "Casuals",
  },
  {
    _id: uuid(),
    title: "Clark's Dark Tan Shoes",
    brand: "Clark's",
    price: 2800,
    inStock:false,
    fastDelivery: true,
    rating: 2,
    imageUrl: "/Assets/dark_tan_moc.jpeg",
    categoryName: "Casuals",
  },
  {
    _id: uuid(),
    title: "Puxton White Sports",
    brand: "Puxton",
    price: 2800,
    inStock:true,
    fastDelivery: false,
    rating: 5,
    imageUrl: "/Assets/puxton_darktan_sports.jpeg",
    categoryName: "Sports",
  },
  {
    _id: uuid(),
    title: "Clark's Tan Sports Shoes",
    brand: "Clark's",
    price: 1800,
    inStock:true,
    fastDelivery: true,
    rating: 4,
    imageUrl: "/Assets/tan_sports.jpeg",
    categoryName: "Sports",
  },
];
